<a href="https://colab.research.google.com/github/joseydyrueda-code/programacion1/blob/main/ultima_semana.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#martes 28 de abril

escritura de archivos desde python

python permite cargar y crear objetos de archivos dados, y tambien permite crear y editar archivos dados

In [ ]:
#crear y escribir un archivo de texto
with open("archivo.txt", "w") as f:
  f.write("hola, este es un archivo de texto.\n")
  f.write("segunda linea.\n")

con el argumento "w" se crea el archivo si no existe. tambien sobreescribe el archivo si ya existe, borrando su contenido previo

con archivos .txt (se tiene que tener en cuenta la forma de separar espacios)

In [ ]:
with open("archivo.txt", "r") as f: #vamos a leer el objeto con la funcion r (ademas de llamar al objeto como f)
  print(f.read())

hola, este es un archivo de texto.
segunda linea.

con el argumento "r" se leen archivos

In [ ]:
from google.colab import files
files.download("archivo.txt")

In [ ]:
#abrir en modo append para editar un archivo ya existente
with open("archivo.txt", "a") as f:
   f.write("\nEsta es una nueva linea añadida") #\n es un espacio

In [ ]:
with open("archivo.txt", "r") as f:
  print(f.read())

hola, este es un archivo de texto.
segunda linea.

Esta es una nueva linea añadida

un ejemplo propio

In [ ]:
with open("archivos.txt", "a") as f:
   f.write("\n lerolerocandelero")

In [ ]:
with open("archivos.txt", "r")as f:
  print(f.read())

 lerolerocandelero
 lerolerocandelero
 lerolerocandelero

In [ ]:
with open("archivo.txt", "w") as d:
  d.write("hola.\n")
  d.write("matematicas.\n")

In [ ]:
with open("archivo.txt", "r") as d:
  print(d.read())

hola.
matematicas.

In [ ]:
from google.colab import files
files.download("archivo.txt")

importar archivos directamente

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving archivo (4).txt to archivo (4).txt

In [ ]:
with open("archivo (1).txt", "w") as f:
    f.write("este archivo fue completamente modificado\n")
    f.write("nueva linea 1\n")
    f.write("nueva linea 2\n")

In [ ]:
with open("archivo (1).txt", "r") as f:
  print(f.read())

este archivo fue completamente modificado
nueva linea 1
nueva linea 2

In [ ]:
from google.colab import files
files.download("archivo (1).txt")

con archivos .csv

In [ ]:
import csv
datos = [
    ["nombre", " edad", " ciudad"],
    ["ana ",  25, " bogota"],
    ["luis ",  30, " medellin"],
    ["carlos ",  28, " cali"]
]

with open("datos.csv", "w", newline="") as f:
    writer = csv.writer(f)
    writer.writerows(datos)

In [ ]:
with open("datos.csv", "r") as f:
  print(f.read())

nombre, edad, ciudad
ana ,25, bogota
luis ,30, medellin
carlos ,28, cali

In [ ]:
files.download("datos.csv")

In [ ]:
from google.colab import drive
drive.mount("/content/drive")

Mounted at /content/drive

In [ ]:
ruta = "/content/drive/MyDrive/datos.csv"
import shutil
shutil.copy("datos.csv", ruta )

'/content/drive/MyDrive/datos.csv'

In [ ]:
with open(ruta, "r") as f:
  print(f.read())

nombre, edad, ciudad
ana ,25, bogota
luis ,30, medellin
carlos ,28, cali

In [ ]:
with open(ruta, "r") as f:
  data = list(csv.reader(f))

  #agregar una nueva fila
  data.append(["diego", 28, "armenia"]) #ajusta segun columnas existentes
  data

In [ ]:
import pandas as pd
data1 = pd.DataFrame(data)
data1

         0      1          2
0   nombre   edad     ciudad
1     ana      25     bogota
2    luis      30   medellin
3  carlos      28       cali
4    diego     28    armenia

In [ ]:
import csv

ruta = "/content/drive/MyDrive/datos.csv"

# Leer
with open(ruta, "r") as f:
    data = list(csv.reader(f))

# Mostrar antes
print("ANTES:")
print(data)

# Agregar fila
data.append(["Diego", "28", "Armenia"])

# Guardar
with open(ruta, "w", newline="") as f:
    writer = csv.writer(f)
    writer.writerows(data)

# Mostrar después
print("\nDESPUÉS:")
with open(ruta, "r") as f:
    print(f.read())

ANTES:
[['nombre', ' edad', ' ciudad'], ['ana ', '25', ' bogota'], ['luis ', '30', ' medellin'], ['carlos ', '28', ' cali']]

DESPUÉS:
nombre, edad, ciudad
ana ,25, bogota
luis ,30, medellin
carlos ,28, cali
Diego,28,Armenia

In [ ]:
import os
os.listdir("/content/drive/MyDrive")

['Colab Notebooks',
 'Fotos',
 'Encuesta: Momentos Inolvidables .gform',
 'Formulario sin título.gform',
 'Copia de Encuesta de clientes potenciales. .gform',
 'Encuesta de clientes potenciales. .gform',
 'Classroom',
 'actualizado de datos_2025.jpg',
 'TI Joseydy Andrea Perozo Rueda. docx',
 'TI_ JOSEYDY ANDREA PEROZO RUEDA.pdf',
 'MODELO CARTA CARNET_2025 (2).pdf',
 'MODELO CARTA CARNET_2025 (1).pdf',
 'TI_ MAHICOL FABIAN TOLOZA GUEVARA.pdf',
 'MODELO CARTA CARNET_2025.pdf',
 'TI_ NICOLAS SANTIAGO JARAMILLO CONTRERAS.pdf',
 'actualizado de datos.jpg',
 'Joseydy Perozo autorización_20251120_202241_0000.pdf',
 'BasicNote',
 'Currículum.gdoc',
 'liquidacionPregradoPresencial_copia (2).pdf',
 'liquidacionPregradoPresencial_copia (1).pdf',
 'liquidacionPregradoPresencial_copia.pdf',
 'horario matemáticas.png',
 'FUNCIONES DE PYTHON.gdoc',
 'TIPOS Y CLASES DE OBJETOS.docx',
 'Documento sin título (3).gdoc',
 'Documento sin título (2).gdoc',
 'Documento sin título (1).gdoc',
 'Álgebra I',
 'Joseydy Andrea Perozo Rueda.gdoc',
 'Joseydy Perozo (covers).pdf',
 'Documento sin título.gdoc',
 'Cover criptografía Perozo Rueda Joseydy Andrea.pdf',
 'geometria-moderna-moise_copia.pdf',
 'datos.csv']

In [ ]:
import pandas as pd
df = pd.read_csv(ruta)
df

    nombre   edad     ciudad
0     ana      25     bogota
1    luis      30   medellin
2  carlos      28       cali
3    Diego     28    Armenia

In [ ]:
df["Nueva_Columna"] = "valor"
df["Nueva_Columna"] = [10, 20, 30, None] #ejemplo
df

    nombre   edad     ciudad  Nueva_Columna
0     ana      25     bogota           10.0
1    luis      30   medellin           20.0
2  carlos      28       cali           30.0
3    Diego     28    Armenia            NaN

#jueves 30 de abril
#manejar otros lenguajes desde consola en python

#manejo de un lenguaje desde un entorno de ejecucion

In [1]:
x = rnorm(100, mean = 6, sd = 1)

In [2]:
summary(x)

   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.
  3.012   5.404   6.078   6.057   6.717   8.030

In [4]:
install.packages("nortest")

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

In [6]:
library(nortest)

In [7]:
ad.test(x)

	Anderson-Darling normality test

data:  x
A = 0.20356, p-value = 0.8727

#manejo de errores y exepciones

In [10]:
x = 10 / 0